version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 80:80
    networks:
      - app-network

  # db:
  #   image: mysql:5.7
  #   container_name: mysql_db
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_DATABASE: my_laravel_app
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allow empty password
  #   ports:
  #     - 3308:3306
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# volumes:
#   mysql_data:
#     driver: local
